name: Feature request
description: Request an improvement or feature
title: '[Feature]: '
labels: [enhancement]
assignees:
  - GrayGalaxy
body:
  - type: markdown
    attributes:
      value: Request a feature that helps to add more functionality or user-experience
  - type: checkboxes
    attributes:
      label: Preflight Checklist
      description: Please ensure you've completed all of the following.
      options:
        - label: I agree to follow the [Code of Conduct](https://github.com/GrayGalaxy/graygalaxy/blob/main/code_of_conduct.md) that this project adheres to.
          required: true
        - label: I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.
          required: true
  - type: textarea
    attributes:
      label: Describe the feature
      description: What would like to add as a feature?
      placeholder: Explain the feature
    validations:
      required: true
  - type: textarea
    attributes:
      label: Suggest how to implement
      description: If you can think of some way you can apply the feature, please let us know
      placeholder: Give an idea how to aply the feature
    validations:
      required: false
